DROP DATABASE marriage;
CREATE DATABASE marriage;

USE marriage;

DROP TABLE t_hello_world;

CREATE TABLE t_hello_world(
  id int NOT NULL PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL ,
  weight FLOAT NOT NULL
) ENGINE=INNODB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;